/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUnitsRouteImport } from './routes/_authenticated/units'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminTenantsRouteImport } from './routes/_authenticated/admin.tenants'
import { Route as AuthenticatedAdminRegistrationsRouteImport } from './routes/_authenticated/admin.registrations'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUnitsRoute = AuthenticatedUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTenantsRoute =
  AuthenticatedAdminTenantsRouteImport.update({
    id: '/admin/tenants',
    path: '/admin/tenants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRegistrationsRoute =
  AuthenticatedAdminRegistrationsRouteImport.update({
    id: '/admin/registrations',
    path: '/admin/registrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/daftar': typeof DaftarRoute
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/units': typeof AuthenticatedUnitsRoute
  '/_authenticated/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/_authenticated/admin/tenants': typeof AuthenticatedAdminTenantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daftar'
    | '/login'
    | '/dashboard'
    | '/units'
    | '/admin/registrations'
    | '/admin/tenants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daftar'
    | '/login'
    | '/dashboard'
    | '/units'
    | '/admin/registrations'
    | '/admin/tenants'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/daftar'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/units'
    | '/_authenticated/admin/registrations'
    | '/_authenticated/admin/tenants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DaftarRoute: typeof DaftarRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/units': {
      id: '/_authenticated/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AuthenticatedUnitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tenants': {
      id: '/_authenticated/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AuthenticatedAdminTenantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/registrations': {
      id: '/_authenticated/admin/registrations'
      path: '/admin/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AuthenticatedAdminRegistrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedUnitsRoute: typeof AuthenticatedUnitsRoute
  AuthenticatedAdminRegistrationsRoute: typeof AuthenticatedAdminRegistrationsRoute
  AuthenticatedAdminTenantsRoute: typeof AuthenticatedAdminTenantsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedUnitsRoute: AuthenticatedUnitsRoute,
  AuthenticatedAdminRegistrationsRoute: AuthenticatedAdminRegistrationsRoute,
  AuthenticatedAdminTenantsRoute: AuthenticatedAdminTenantsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DaftarRoute: DaftarRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
