/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUnitsRouteImport } from './routes/_authenticated/units'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoaRouteImport } from './routes/_authenticated/coa'
import { Route as AuthenticatedJournalsIndexRouteImport } from './routes/_authenticated/journals.index'
import { Route as AuthenticatedReportsTrialBalanceRouteImport } from './routes/_authenticated/reports.trial-balance'
import { Route as AuthenticatedJournalsNewRouteImport } from './routes/_authenticated/journals.new'
import { Route as AuthenticatedAdminTenantsRouteImport } from './routes/_authenticated/admin.tenants'
import { Route as AuthenticatedAdminRegistrationsRouteImport } from './routes/_authenticated/admin.registrations'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUnitsRoute = AuthenticatedUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoaRoute = AuthenticatedCoaRouteImport.update({
  id: '/coa',
  path: '/coa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJournalsIndexRoute =
  AuthenticatedJournalsIndexRouteImport.update({
    id: '/journals/',
    path: '/journals/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsTrialBalanceRoute =
  AuthenticatedReportsTrialBalanceRouteImport.update({
    id: '/reports/trial-balance',
    path: '/reports/trial-balance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJournalsNewRoute =
  AuthenticatedJournalsNewRouteImport.update({
    id: '/journals/new',
    path: '/journals/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTenantsRoute =
  AuthenticatedAdminTenantsRouteImport.update({
    id: '/admin/tenants',
    path: '/admin/tenants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRegistrationsRoute =
  AuthenticatedAdminRegistrationsRouteImport.update({
    id: '/admin/registrations',
    path: '/admin/registrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/login': typeof LoginRoute
  '/coa': typeof AuthenticatedCoaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/journals/new': typeof AuthenticatedJournalsNewRoute
  '/reports/trial-balance': typeof AuthenticatedReportsTrialBalanceRoute
  '/journals/': typeof AuthenticatedJournalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/login': typeof LoginRoute
  '/coa': typeof AuthenticatedCoaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/journals/new': typeof AuthenticatedJournalsNewRoute
  '/reports/trial-balance': typeof AuthenticatedReportsTrialBalanceRoute
  '/journals': typeof AuthenticatedJournalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/daftar': typeof DaftarRoute
  '/login': typeof LoginRoute
  '/_authenticated/coa': typeof AuthenticatedCoaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/units': typeof AuthenticatedUnitsRoute
  '/_authenticated/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/_authenticated/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/_authenticated/journals/new': typeof AuthenticatedJournalsNewRoute
  '/_authenticated/reports/trial-balance': typeof AuthenticatedReportsTrialBalanceRoute
  '/_authenticated/journals/': typeof AuthenticatedJournalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daftar'
    | '/login'
    | '/coa'
    | '/dashboard'
    | '/units'
    | '/admin/registrations'
    | '/admin/tenants'
    | '/journals/new'
    | '/reports/trial-balance'
    | '/journals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daftar'
    | '/login'
    | '/coa'
    | '/dashboard'
    | '/units'
    | '/admin/registrations'
    | '/admin/tenants'
    | '/journals/new'
    | '/reports/trial-balance'
    | '/journals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/daftar'
    | '/login'
    | '/_authenticated/coa'
    | '/_authenticated/dashboard'
    | '/_authenticated/units'
    | '/_authenticated/admin/registrations'
    | '/_authenticated/admin/tenants'
    | '/_authenticated/journals/new'
    | '/_authenticated/reports/trial-balance'
    | '/_authenticated/journals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DaftarRoute: typeof DaftarRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/units': {
      id: '/_authenticated/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AuthenticatedUnitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coa': {
      id: '/_authenticated/coa'
      path: '/coa'
      fullPath: '/coa'
      preLoaderRoute: typeof AuthenticatedCoaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journals/': {
      id: '/_authenticated/journals/'
      path: '/journals'
      fullPath: '/journals/'
      preLoaderRoute: typeof AuthenticatedJournalsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/trial-balance': {
      id: '/_authenticated/reports/trial-balance'
      path: '/reports/trial-balance'
      fullPath: '/reports/trial-balance'
      preLoaderRoute: typeof AuthenticatedReportsTrialBalanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journals/new': {
      id: '/_authenticated/journals/new'
      path: '/journals/new'
      fullPath: '/journals/new'
      preLoaderRoute: typeof AuthenticatedJournalsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tenants': {
      id: '/_authenticated/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AuthenticatedAdminTenantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/registrations': {
      id: '/_authenticated/admin/registrations'
      path: '/admin/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AuthenticatedAdminRegistrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCoaRoute: typeof AuthenticatedCoaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedUnitsRoute: typeof AuthenticatedUnitsRoute
  AuthenticatedAdminRegistrationsRoute: typeof AuthenticatedAdminRegistrationsRoute
  AuthenticatedAdminTenantsRoute: typeof AuthenticatedAdminTenantsRoute
  AuthenticatedJournalsNewRoute: typeof AuthenticatedJournalsNewRoute
  AuthenticatedReportsTrialBalanceRoute: typeof AuthenticatedReportsTrialBalanceRoute
  AuthenticatedJournalsIndexRoute: typeof AuthenticatedJournalsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCoaRoute: AuthenticatedCoaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedUnitsRoute: AuthenticatedUnitsRoute,
  AuthenticatedAdminRegistrationsRoute: AuthenticatedAdminRegistrationsRoute,
  AuthenticatedAdminTenantsRoute: AuthenticatedAdminTenantsRoute,
  AuthenticatedJournalsNewRoute: AuthenticatedJournalsNewRoute,
  AuthenticatedReportsTrialBalanceRoute: AuthenticatedReportsTrialBalanceRoute,
  AuthenticatedJournalsIndexRoute: AuthenticatedJournalsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DaftarRoute: DaftarRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
